# Generated by Django 3.2.6 on 2025-03-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=20)),
                ('pass1', models.CharField(max_length=20)),
                ('repass', models.CharField(max_length=20)),
                ('gen', models.CharField(max_length=20)),
            ],
        ),
    ]
