# Generated by Django 3.2.6 on 2025-03-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField()),
                ('dt1', models.CharField(max_length=30)),
                ('fname', models.CharField(max_length=30)),
                ('seats', models.IntegerField()),
                ('source', models.CharField(max_length=30)),
                ('dest', models.CharField(max_length=30)),
                ('prize', models.IntegerField()),
                ('dt2', models.CharField(max_length=30)),
            ],
        ),
    ]
